language: generic

branches:
  only:
    - master
env:
  global:
    - ENCRYPTION_LABEL="aec5871fe877"
    - DEPLOY_USER="dh_ckhcfv"
    - SERVER="64.111.126.30"
    - SERVER_PUBLIC_KEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD6qoSdZpEXLsUSm5ANlybl39Ycq+utYZ30yvFD66+iMVcrnPIRN8lhvPMaJpIOYPk8htthU7f4VskMadEU50mzdF0wJ1nEnU37s/86JZ3/uSW4z0jS6nsD6AwqknBP3mBCnAE2Hd7IpWD6LIKWbKPjz/hcgxxztT5/DmbSmNzva+MN5lN5ehWFuRXCgOOSTBU1FTAS/NggV4Z+dD9dZJTvLpY2Tacjhn/k/rq4xmsA96HDUT9EcLWBAV+Vo5a7fhPeLTDJ13jGPJRZqx6g58Wd3NVLvRlQweehcKQldUxiB4BvoryxKEViMHT0bkWl02HyXvqZaBM0kMjUqjbRp28p"
    - WEB_ROOT="whatwg.org.quuz.org"
script:
  - bash ./deploy.sh
notifications:
  email:
    on_success: never
    on_failure: always
